version: '3'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  nginx:
    build:
      context: ../
      dockerfile: nginx/Dockerfile
    ports:
      - 8080:80
